# Generated by Django 3.1.3 on 2020-11-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('accident', models.BooleanField()),
                ('repair', models.TextField()),
                ('manufacturer', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('accident', models.BooleanField()),
                ('repair', models.TextField()),
                ('manufacturer', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
