# Generated by Django 3.1.3 on 2020-11-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='accident',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='repair',
            field=models.TextField(blank=True, null=True),
        ),
    ]
